# Generated by Django 4.2.3 on 2023-08-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Transmission"
            ),
            preserve_default=False,
        ),
    ]
