# Generated by Django 4.2.3 on 2023-08-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0003_vehicle_engine_type_vehicle_euro_standard_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Vehicle Brand",
            },
        ),
        migrations.CreateModel(
            name="VehicleColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleEngine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_engine",
                    models.CharField(
                        choices=[
                            ("Diesel", "Diesel"),
                            ("Petrol", "Petrol"),
                            ("LPG", "LPG"),
                            ("Electric", "Electric"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=8,
                        verbose_name="Engine Type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleEuroStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_standard",
                    models.CharField(
                        choices=[
                            ("EURO-1", "EURO1"),
                            ("EURO-2", "EURO2"),
                            ("EURO-3", "EURO3"),
                            ("EURO-4", "EURO4"),
                            ("EURO-5", "EURO5"),
                            ("EURO-6", "EURO6"),
                        ],
                        max_length=6,
                        verbose_name="Euro Standard",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleManufacturingYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_manufacturing_year",
                    models.CharField(
                        choices=[
                            ("1930", "YEAR_1930"),
                            ("1931", "YEAR_1931"),
                            ("1932", "YEAR_1932"),
                            ("1933", "YEAR_1933"),
                            ("1934", "YEAR_1934"),
                            ("1935", "YEAR_1935"),
                            ("1936", "YEAR_1936"),
                            ("1937", "YEAR_1937"),
                            ("1938", "YEAR_1938"),
                            ("1939", "YEAR_1939"),
                            ("1940", "YEAR_1940"),
                            ("1941", "YEAR_1941"),
                            ("1942", "YEAR_1942"),
                            ("1943", "YEAR_1943"),
                            ("1944", "YEAR_1944"),
                            ("1945", "YEAR_1945"),
                            ("1946", "YEAR_1946"),
                            ("1947", "YEAR_1947"),
                            ("1948", "YEAR_1948"),
                            ("1949", "YEAR_1949"),
                            ("1950", "YEAR_1950"),
                            ("1951", "YEAR_1951"),
                            ("1952", "YEAR_1952"),
                            ("1953", "YEAR_1953"),
                            ("1954", "YEAR_1954"),
                            ("1955", "YEAR_1955"),
                            ("1956", "YEAR_1956"),
                            ("1957", "YEAR_1957"),
                            ("1958", "YEAR_1958"),
                            ("1959", "YEAR_1959"),
                            ("1960", "YEAR_1960"),
                            ("1961", "YEAR_1961"),
                            ("1962", "YEAR_1962"),
                            ("1963", "YEAR_1963"),
                            ("1964", "YEAR_1964"),
                            ("1965", "YEAR_1965"),
                            ("1966", "YEAR_1966"),
                            ("1967", "YEAR_1967"),
                            ("1968", "YEAR_1968"),
                            ("1969", "YEAR_1969"),
                            ("1970", "YEAR_1970"),
                            ("1971", "YEAR_1971"),
                            ("1972", "YEAR_1972"),
                            ("1973", "YEAR_1973"),
                            ("1974", "YEAR_1974"),
                            ("1975", "YEAR_1975"),
                            ("1976", "YEAR_1976"),
                            ("1977", "YEAR_1977"),
                            ("1978", "YEAR_1978"),
                            ("1979", "YEAR_1979"),
                            ("1980", "YEAR_1980"),
                            ("1981", "YEAR_1981"),
                            ("1982", "YEAR_1982"),
                            ("1983", "YEAR_1983"),
                            ("1984", "YEAR_1984"),
                            ("1985", "YEAR_1985"),
                            ("1986", "YEAR_1986"),
                            ("1987", "YEAR_1987"),
                            ("1988", "YEAR_1988"),
                            ("1989", "YEAR_1989"),
                            ("1990", "YEAR_1990"),
                            ("1991", "YEAR_1991"),
                            ("1992", "YEAR_1992"),
                            ("1993", "YEAR_1993"),
                            ("1994", "YEAR_1994"),
                            ("1995", "YEAR_1995"),
                            ("1996", "YEAR_1996"),
                            ("1997", "YEAR_1997"),
                            ("1998", "YEAR_1998"),
                            ("1999", "YEAR_1999"),
                            ("2000", "YEAR_2000"),
                            ("2001", "YEAR_2001"),
                            ("2002", "YEAR_2002"),
                            ("2003", "YEAR_2003"),
                            ("2004", "YEAR_2004"),
                            ("2005", "YEAR_2005"),
                            ("2006", "YEAR_2006"),
                            ("2007", "YEAR_2007"),
                            ("2008", "YEAR_2008"),
                            ("2009", "YEAR_2009"),
                            ("2010", "YEAR_2010"),
                            ("2011", "YEAR_2011"),
                            ("2012", "YEAR_2012"),
                            ("2013", "YEAR_2013"),
                            ("2014", "YEAR_2014"),
                            ("2015", "YEAR_2015"),
                            ("2016", "YEAR_2016"),
                            ("2017", "YEAR_2017"),
                            ("2018", "YEAR_2018"),
                            ("2019", "YEAR_2019"),
                            ("2020", "YEAR_2020"),
                            ("2021", "YEAR_2021"),
                            ("2022", "YEAR_2022"),
                            ("2023", "YEAR_2023"),
                        ],
                        max_length=4,
                        verbose_name="Manufacturing Year",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Vehicle Model",
            },
        ),
        migrations.CreateModel(
            name="VehicleTransmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_transmission",
                    models.CharField(
                        choices=[
                            ("Manual", "MANUAL"),
                            ("Automatic", "AUTOMATIC"),
                            ("CVT", "CVT"),
                            ("Semi-Automatic", "SEMI_AUTOMATIC"),
                        ],
                        max_length=14,
                        verbose_name="Transmission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="vehicle_model",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="vehicles.vehiclemodel",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="vehicles.vehiclebrand"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicles.vehiclecolor",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="engine_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="vehicles.vehicleengine"
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="euro_standard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="vehicles.vehicleeurostandard",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="manufacturing_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="vehicles.vehiclemanufacturingyear",
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="transmission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="vehicles.vehicletransmission",
            ),
        ),
    ]
