# Generated by Django 4.2.3 on 2023-08-24 13:02

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sellerprofile_seller_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerprofile",
            name="seller_image",
        ),
        migrations.CreateModel(
            name="ProfileImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="Profile Image"
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_image",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
        ),
    ]
