# Generated by Django 4.2.3 on 2023-08-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_sellerprofile_seller_image_profileimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profileimage",
            old_name="vehicle_image",
            new_name="profile_image",
        ),
        migrations.RenameField(
            model_name="profileimage",
            old_name="vehicle",
            new_name="profile_img",
        ),
    ]
