# Generated by Django 4.2.3 on 2023-08-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_vehicle_image_profileimage_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profileimage",
            name="profile_img",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_image",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
