# Generated by Django 4.2.3 on 2023-09-05 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profileimage_profile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sellerprofile",
            name="first_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "First name must be at least 3 characters long"
                    )
                ],
                verbose_name="First Name",
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="last_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.MinLengthValidator(
                        3, "Last name must be at least 3 characters long"
                    )
                ],
                verbose_name="Last Name",
            ),
        ),
    ]
